# PANDAS

In [4]:
import pandas as pd
import numpy as np

In [6]:
df1 =pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())

In [7]:
df1

score1    score2    score3    score4    score5
A  0.782864  0.257921  0.248293  0.422572  0.336259
B  0.249203  0.954687  0.481991  0.352690  0.141297
C  0.138356  0.351275  0.605092  0.335219  0.120426
D  0.275137  0.511834  0.378834  0.725001  0.455009
E  0.036275  0.147889  0.921004  0.038123  0.816545
F  0.316588  0.036132  0.997916  0.599118  0.530591
G  0.412780  0.710580  0.777684  0.725167  0.973674
H  0.222246  0.049227  0.069740  0.863076  0.559055

In [9]:
df1.drop(['score1','score2'],axis=1)

score3    score4    score5
A  0.248293  0.422572  0.336259
B  0.481991  0.352690  0.141297
C  0.605092  0.335219  0.120426
D  0.378834  0.725001  0.455009
E  0.921004  0.038123  0.816545
F  0.997916  0.599118  0.530591
G  0.777684  0.725167  0.973674
H  0.069740  0.863076  0.559055

In [11]:
df1['score6']=df1['score1']+df1['score2']

In [12]:
df1

score1    score2    score3    score4    score5    score6
A  0.782864  0.257921  0.248293  0.422572  0.336259  1.040785
B  0.249203  0.954687  0.481991  0.352690  0.141297  1.203890
C  0.138356  0.351275  0.605092  0.335219  0.120426  0.489631
D  0.275137  0.511834  0.378834  0.725001  0.455009  0.786971
E  0.036275  0.147889  0.921004  0.038123  0.816545  0.184164
F  0.316588  0.036132  0.997916  0.599118  0.530591  0.352719
G  0.412780  0.710580  0.777684  0.725167  0.973674  1.123360
H  0.222246  0.049227  0.069740  0.863076  0.559055  0.271472

In [13]:
df2 ={'ID':[101,102,104],'Name':['Jhon','Mercy','Akhil'],'Age':[22,25,24]}
df =pd.DataFrame(df2)
df

ID   Name  Age
0  101   Jhon   22
1  102  Mercy   25
2  104  Akhil   24

In [18]:
df[['Age','Name']]

Age   Name
0   22   Jhon
1   25  Mercy
2   24  Akhil

In [20]:
df.drop(['Name','Age'],axis=1) #axis =1 it will search in columns

ID
0  101
1  102
2  104

In [21]:
df

ID   Name  Age
0  101   Jhon   22
1  102  Mercy   25
2  104  Akhil   24

In [36]:
np1=np.zeros(10)# assessment

In [29]:
np1[4]=1

In [30]:
np1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [33]:
np2=np.arange(10,66)

In [35]:
np2[: :-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [38]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])